const productsArray = [
    {
        id: 1,
        name: 'iPhone XS',
        description: 'This is iPhone XS',
        type: 'phone',
        color: 'red',
        price: 500,
        image: '/images/iphone11-black.jpg',
    },
    {
        id: 2,
        name: 'iPhone 7',
        description: 'This is iPhone 7',
        type: 'phone',
        color: 'gray',
        price: 600,
        image: '/images/iphone12-mint.jpg',
    },
    {
        id: 3,
        name: 'iPhone 6s',
        description: 'This is iPhone 6s',
        type: 'phone',
        color: 'black',
        price: 300,
        image: '/images/iphone13-blue.jpg',
    },
    {
        id: 4,
        name: 'iPhone 5',
        description: 'This is iPhone 5',
        type: 'phone',
        color: 'white',
        price: 250,
        image: '/images/iphone13-pink.jpg',
    },
    {
        id: 5,
        name: 'iPhone 5s',
        description: 'This is iPhone 5s',
        type: 'phone',
        color: 'space gray',
        price: 180,
        image: '/images/iphone13-red.jpg',
    },
    {
        id: 6,
        name: 'iPhone 4s',
        description: 'This is iPhone 4s',
        type: 'phone',
        color: 'gray',
        price: 100,
        image: '/images/iphone13pro-gold.jpg',
    },
]

export default productsArray
